### ISSUE TITLE
关于SDA的一些问题

### ISSUE THREAD

**Issue by endeavorman** [caoql98/progressively-dual-prior-guided-few-shot-semantic-segmentation#1]
你好！
想问一下，Scale-Aware Detailed Matching for Few-Shot Aerial Image Semantic Segmentation这篇论文的源码能开源吗？之前在github上有看到iSAID-5i的数据集，现在也找不到了。麻烦啦

**Comment by caoql98** [comment]
您好，数据集和代码已经开源了
